epochs: 2
train_batch_size: 4096
eval_batch_size: 4096
neg_sampling: ~
load_col:
         inter: [user_id, item_id, rating, timestamp]
         user: [user_id, zip_code] #  age, gender, occupation, zip_code]
LABEL_FIELD: rating
unused_col:
    inter: [timestamp]
threshold:
    rating: 3
TIME_FIELD: timestamp
eval_args:
    group_by: user
    order: TO
    mode: uni1000 

benchmark_filename: ['part1', 'part2', 'part3']

metrics: ['Precision', 'Recall', 'MRR', 'NDCG', 'Hit', 'ItemCoverage', 'GiniIndex', 'ShannonEntropy']
topk: 50
valid_metric: MRR@50
metric_decimal_place: 4
eval_step: 10
save_dataset: True
save_dataloaders: True
reproducibility: True
seed: 2020
filter_inter_by_user_or_item: True
user_inter_num_interval: [20, 1500]